package com.tsystems.si.aviation.imf.vzHandle.db.bean;
// Generated Jun 23, 2016 4:34:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ComFlight generated by hbm2java
 */
public class ComFlight implements java.io.Serializable {

	private Integer id;
	private String owner;
	private Date flightScheduledDate;
	private String flightNumber;
	private String flightDirection;
	private String flightServiceType;
	private Date flightScheduledDateTime;
	private String registration;
	private String callSign;
	private String codeShareFlight;
	private String route;
	private Date scheduledPreviousAirportDepartureDateTime;
	private Date estimatedPreviousAirportDepartureDateTime;
	private Date actualPreviousAirportDepartureDateTime;
	private Date scheduledLandingDateTime;
	private Date estimatedLandingDateTime;
	private Date actualLandingDateTime;
	private Date scheduledOnBlockDateTime;
	private Date estimatedOnBlockDateTime;
	private Date actualOnBlockDateTime;
	private Date scheduledOffBlockDateTime;
	private Date estimatedOffBlockDateTime;
	private Date actualOffBlockDateTime;
	private Date scheduledTakeOffDateTime;
	private Date estimatedTakeOffDateTime;
	private Date actualTakeOffDateTime;
	private String flightStatus;
	private String operationStatus;
	private Date createDateTime;
	private Date updateDateTime;

	public ComFlight() {
	}

	public ComFlight(Date flightScheduledDate, String flightNumber, String flightDirection) {
		this.flightScheduledDate = flightScheduledDate;
		this.flightNumber = flightNumber;
		this.flightDirection = flightDirection;
	}

	public ComFlight(String owner, Date flightScheduledDate, String flightNumber, String flightDirection,
			String flightServiceType, Date flightScheduledDateTime, String registration, String callSign,
			String codeShareFlight, String route, Date scheduledPreviousAirportDepartureDateTime,
			Date estimatedPreviousAirportDepartureDateTime, Date actualPreviousAirportDepartureDateTime,
			Date scheduledLandingDateTime, Date estimatedLandingDateTime, Date actualLandingDateTime,
			Date scheduledOnBlockDateTime, Date estimatedOnBlockDateTime, Date actualOnBlockDateTime,
			Date scheduledOffBlockDateTime, Date estimatedOffBlockDateTime, Date actualOffBlockDateTime,
			Date scheduledTakeOffDateTime, Date estimatedTakeOffDateTime, Date actualTakeOffDateTime,
			String flightStatus, String operationStatus, Date createDateTime, Date updateDateTime) {
		this.owner = owner;
		this.flightScheduledDate = flightScheduledDate;
		this.flightNumber = flightNumber;
		this.flightDirection = flightDirection;
		this.flightServiceType = flightServiceType;
		this.flightScheduledDateTime = flightScheduledDateTime;
		this.registration = registration;
		this.callSign = callSign;
		this.codeShareFlight = codeShareFlight;
		this.route = route;
		this.scheduledPreviousAirportDepartureDateTime = scheduledPreviousAirportDepartureDateTime;
		this.estimatedPreviousAirportDepartureDateTime = estimatedPreviousAirportDepartureDateTime;
		this.actualPreviousAirportDepartureDateTime = actualPreviousAirportDepartureDateTime;
		this.scheduledLandingDateTime = scheduledLandingDateTime;
		this.estimatedLandingDateTime = estimatedLandingDateTime;
		this.actualLandingDateTime = actualLandingDateTime;
		this.scheduledOnBlockDateTime = scheduledOnBlockDateTime;
		this.estimatedOnBlockDateTime = estimatedOnBlockDateTime;
		this.actualOnBlockDateTime = actualOnBlockDateTime;
		this.scheduledOffBlockDateTime = scheduledOffBlockDateTime;
		this.estimatedOffBlockDateTime = estimatedOffBlockDateTime;
		this.actualOffBlockDateTime = actualOffBlockDateTime;
		this.scheduledTakeOffDateTime = scheduledTakeOffDateTime;
		this.estimatedTakeOffDateTime = estimatedTakeOffDateTime;
		this.actualTakeOffDateTime = actualTakeOffDateTime;
		this.flightStatus = flightStatus;
		this.operationStatus = operationStatus;
		this.createDateTime = createDateTime;
		this.updateDateTime = updateDateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public Date getFlightScheduledDate() {
		return this.flightScheduledDate;
	}

	public void setFlightScheduledDate(Date flightScheduledDate) {
		this.flightScheduledDate = flightScheduledDate;
	}

	public String getFlightNumber() {
		return this.flightNumber;
	}

	public void setFlightNumber(String flightNumber) {
		this.flightNumber = flightNumber;
	}

	public String getFlightDirection() {
		return this.flightDirection;
	}

	public void setFlightDirection(String flightDirection) {
		this.flightDirection = flightDirection;
	}

	public String getFlightServiceType() {
		return this.flightServiceType;
	}

	public void setFlightServiceType(String flightServiceType) {
		this.flightServiceType = flightServiceType;
	}

	public Date getFlightScheduledDateTime() {
		return this.flightScheduledDateTime;
	}

	public void setFlightScheduledDateTime(Date flightScheduledDateTime) {
		this.flightScheduledDateTime = flightScheduledDateTime;
	}

	public String getRegistration() {
		return this.registration;
	}

	public void setRegistration(String registration) {
		this.registration = registration;
	}

	public String getCallSign() {
		return this.callSign;
	}

	public void setCallSign(String callSign) {
		this.callSign = callSign;
	}

	public String getCodeShareFlight() {
		return this.codeShareFlight;
	}

	public void setCodeShareFlight(String codeShareFlight) {
		this.codeShareFlight = codeShareFlight;
	}

	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	public Date getScheduledPreviousAirportDepartureDateTime() {
		return this.scheduledPreviousAirportDepartureDateTime;
	}

	public void setScheduledPreviousAirportDepartureDateTime(Date scheduledPreviousAirportDepartureDateTime) {
		this.scheduledPreviousAirportDepartureDateTime = scheduledPreviousAirportDepartureDateTime;
	}

	public Date getEstimatedPreviousAirportDepartureDateTime() {
		return this.estimatedPreviousAirportDepartureDateTime;
	}

	public void setEstimatedPreviousAirportDepartureDateTime(Date estimatedPreviousAirportDepartureDateTime) {
		this.estimatedPreviousAirportDepartureDateTime = estimatedPreviousAirportDepartureDateTime;
	}

	public Date getActualPreviousAirportDepartureDateTime() {
		return this.actualPreviousAirportDepartureDateTime;
	}

	public void setActualPreviousAirportDepartureDateTime(Date actualPreviousAirportDepartureDateTime) {
		this.actualPreviousAirportDepartureDateTime = actualPreviousAirportDepartureDateTime;
	}

	public Date getScheduledLandingDateTime() {
		return this.scheduledLandingDateTime;
	}

	public void setScheduledLandingDateTime(Date scheduledLandingDateTime) {
		this.scheduledLandingDateTime = scheduledLandingDateTime;
	}

	public Date getEstimatedLandingDateTime() {
		return this.estimatedLandingDateTime;
	}

	public void setEstimatedLandingDateTime(Date estimatedLandingDateTime) {
		this.estimatedLandingDateTime = estimatedLandingDateTime;
	}

	public Date getActualLandingDateTime() {
		return this.actualLandingDateTime;
	}

	public void setActualLandingDateTime(Date actualLandingDateTime) {
		this.actualLandingDateTime = actualLandingDateTime;
	}

	public Date getScheduledOnBlockDateTime() {
		return this.scheduledOnBlockDateTime;
	}

	public void setScheduledOnBlockDateTime(Date scheduledOnBlockDateTime) {
		this.scheduledOnBlockDateTime = scheduledOnBlockDateTime;
	}

	public Date getEstimatedOnBlockDateTime() {
		return this.estimatedOnBlockDateTime;
	}

	public void setEstimatedOnBlockDateTime(Date estimatedOnBlockDateTime) {
		this.estimatedOnBlockDateTime = estimatedOnBlockDateTime;
	}

	public Date getActualOnBlockDateTime() {
		return this.actualOnBlockDateTime;
	}

	public void setActualOnBlockDateTime(Date actualOnBlockDateTime) {
		this.actualOnBlockDateTime = actualOnBlockDateTime;
	}

	public Date getScheduledOffBlockDateTime() {
		return this.scheduledOffBlockDateTime;
	}

	public void setScheduledOffBlockDateTime(Date scheduledOffBlockDateTime) {
		this.scheduledOffBlockDateTime = scheduledOffBlockDateTime;
	}

	public Date getEstimatedOffBlockDateTime() {
		return this.estimatedOffBlockDateTime;
	}

	public void setEstimatedOffBlockDateTime(Date estimatedOffBlockDateTime) {
		this.estimatedOffBlockDateTime = estimatedOffBlockDateTime;
	}

	public Date getActualOffBlockDateTime() {
		return this.actualOffBlockDateTime;
	}

	public void setActualOffBlockDateTime(Date actualOffBlockDateTime) {
		this.actualOffBlockDateTime = actualOffBlockDateTime;
	}

	public Date getScheduledTakeOffDateTime() {
		return this.scheduledTakeOffDateTime;
	}

	public void setScheduledTakeOffDateTime(Date scheduledTakeOffDateTime) {
		this.scheduledTakeOffDateTime = scheduledTakeOffDateTime;
	}

	public Date getEstimatedTakeOffDateTime() {
		return this.estimatedTakeOffDateTime;
	}

	public void setEstimatedTakeOffDateTime(Date estimatedTakeOffDateTime) {
		this.estimatedTakeOffDateTime = estimatedTakeOffDateTime;
	}

	public Date getActualTakeOffDateTime() {
		return this.actualTakeOffDateTime;
	}

	public void setActualTakeOffDateTime(Date actualTakeOffDateTime) {
		this.actualTakeOffDateTime = actualTakeOffDateTime;
	}

	public String getFlightStatus() {
		return this.flightStatus;
	}

	public void setFlightStatus(String flightStatus) {
		this.flightStatus = flightStatus;
	}

	public String getOperationStatus() {
		return this.operationStatus;
	}

	public void setOperationStatus(String operationStatus) {
		this.operationStatus = operationStatus;
	}

	public Date getCreateDateTime() {
		return this.createDateTime;
	}

	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}

	public Date getUpdateDateTime() {
		return this.updateDateTime;
	}

	public void setUpdateDateTime(Date updateDateTime) {
		this.updateDateTime = updateDateTime;
	}

}
