package com.tsystems.si.aviation.imf.vzHandle.db.bean;
// Generated Jun 23, 2016 4:34:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Flight generated by hbm2java
 */
public class Flight implements java.io.Serializable {

	/** 
	 * serialVersionUID:TODO
	 * 
	 */  
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Date flightScheduledDate;
	private String flightNumber;
	private String flightDirection;
	private String airlineIatacode;
	private String airlineIcaocode;
	private String aircraftIatacode;
	private String aircraftIcaocode;
	private String flightServiceType;
	private String flightCountryType;
	private Date flightScheduledDateTime;
	private String registration;
	private String callSign;
	private String codeShareFlight;
	private String iataoriginAirport;
	private String iatapreviousAirport;
	private String iataviaAirport;
	private String iatanextAirport;
	private String iatadestinationAirport;
	private String route;
	private Date scheduledPreviousAirportDepartureDateTime;
	private Date estimatedPreviousAirportDepartureDateTime;
	private Date actualPreviousAirportDepartureDateTime;
	private Date scheduledLandingDateTime;
	private Date estimatedLandingDateTime;
	private Date actualLandingDateTime;
	private Date scheduledOnBlockDateTime;
	private Date estimatedOnBlockDateTime;
	private Date actualOnBlockDateTime;
	private Date scheduledOffBlockDateTime;
	private Date estimatedOffBlockDateTime;
	private Date actualOffBlockDateTime;
	private Date scheduledTakeOffDateTime;
	private Date estimatedTakeOffDateTime;
	private Date actualTakeOffDateTime;
	private Integer scheduledFlyTime;
	private Integer estimatedFlyTime;
	private Date actualDoorOpenDateTime;
	private Date actualDoorCloseDateTime;
	private Date actualOnBridgeDateTime;
	private Date actualOffBridgeDateTime;
	private Date bestKnownDateTime;
	private String flightStatus;
	private String operationStatus;
	private String delayReasonCode;
	private String delayReasonText;
	private String publicTextComment;
	private String createReason;
	private String diversionAirportIatacode;
	private String diversionAirportIcaocode;
	private String changeLandingAirportIatacode;
	private String changeLandingAirportIcaocode;
	private String displayCode;
	private String isTransitFlight;
	private String isOverNightFlight;
	private String isVipflight;
	private String vipcomment;
	private String stand;
	private String groundMovement;
	private String gate;
	private String gateStatus;
	private Date scheduledGateStartDateTime;
	private Date scheduledGateEndDateTime;
	private Date actualGateStartDateTime;
	private Date actualGateEndDateTime;
	private String baggageReclaim;
	private String baggageMakeup;
	private String checkInDesk;
	private Integer checkInPassengerCount;
	private Integer securityCheckPassengerCount;
	private Integer onboardPassengerCount;
	private Date createDateTime;
	private Date updateDateTime;
	private String fuid;

	public Flight() {
	}

	public Flight(Date flightScheduledDate, String flightNumber, String flightDirection) {
		this.flightScheduledDate = flightScheduledDate;
		this.flightNumber = flightNumber;
		this.flightDirection = flightDirection;
	}

	public Flight(Date flightScheduledDate, String flightNumber, String flightDirection, String airlineIatacode,
			String airlineIcaocode, String aircraftIatacode, String aircraftIcaocode, String flightServiceType,
			String flightCountryType, Date flightScheduledDateTime, String registration, String callSign,
			String codeShareFlight, String iataoriginAirport, String iatapreviousAirport, String iataviaAirport,
			String iatanextAirport, String iatadestinationAirport, String route,
			Date scheduledPreviousAirportDepartureDateTime, Date estimatedPreviousAirportDepartureDateTime,
			Date actualPreviousAirportDepartureDateTime, Date scheduledLandingDateTime, Date estimatedLandingDateTime,
			Date actualLandingDateTime, Date scheduledOnBlockDateTime, Date estimatedOnBlockDateTime,
			Date actualOnBlockDateTime, Date scheduledOffBlockDateTime, Date estimatedOffBlockDateTime,
			Date actualOffBlockDateTime, Date scheduledTakeOffDateTime, Date estimatedTakeOffDateTime,
			Date actualTakeOffDateTime, Integer scheduledFlyTime, Integer estimatedFlyTime, Date actualDoorOpenDateTime,
			Date actualDoorCloseDateTime, Date actualOnBridgeDateTime, Date actualOffBridgeDateTime,
			Date bestKnownDateTime, String flightStatus, String operationStatus, String delayReasonCode,
			String delayReasonText, String publicTextComment, String createReason, String diversionAirportIatacode,
			String diversionAirportIcaocode, String changeLandingAirportIatacode, String changeLandingAirportIcaocode,
			String displayCode, String isTransitFlight, String isOverNightFlight, String isVipflight, String vipcomment,
			String stand, String groundMovement, String gate, String gateStatus, Date scheduledGateStartDateTime,
			Date scheduledGateEndDateTime, Date actualGateStartDateTime, Date actualGateEndDateTime,
			String baggageReclaim, String baggageMakeup, String checkInDesk, Integer checkInPassengerCount,
			Integer securityCheckPassengerCount, Integer onboardPassengerCount, Date createDateTime,
			Date updateDateTime, String fuid) {
		this.flightScheduledDate = flightScheduledDate;
		this.flightNumber = flightNumber;
		this.flightDirection = flightDirection;
		this.airlineIatacode = airlineIatacode;
		this.airlineIcaocode = airlineIcaocode;
		this.aircraftIatacode = aircraftIatacode;
		this.aircraftIcaocode = aircraftIcaocode;
		this.flightServiceType = flightServiceType;
		this.flightCountryType = flightCountryType;
		this.flightScheduledDateTime = flightScheduledDateTime;
		this.registration = registration;
		this.callSign = callSign;
		this.codeShareFlight = codeShareFlight;
		this.iataoriginAirport = iataoriginAirport;
		this.iatapreviousAirport = iatapreviousAirport;
		this.iataviaAirport = iataviaAirport;
		this.iatanextAirport = iatanextAirport;
		this.iatadestinationAirport = iatadestinationAirport;
		this.route = route;
		this.scheduledPreviousAirportDepartureDateTime = scheduledPreviousAirportDepartureDateTime;
		this.estimatedPreviousAirportDepartureDateTime = estimatedPreviousAirportDepartureDateTime;
		this.actualPreviousAirportDepartureDateTime = actualPreviousAirportDepartureDateTime;
		this.scheduledLandingDateTime = scheduledLandingDateTime;
		this.estimatedLandingDateTime = estimatedLandingDateTime;
		this.actualLandingDateTime = actualLandingDateTime;
		this.scheduledOnBlockDateTime = scheduledOnBlockDateTime;
		this.estimatedOnBlockDateTime = estimatedOnBlockDateTime;
		this.actualOnBlockDateTime = actualOnBlockDateTime;
		this.scheduledOffBlockDateTime = scheduledOffBlockDateTime;
		this.estimatedOffBlockDateTime = estimatedOffBlockDateTime;
		this.actualOffBlockDateTime = actualOffBlockDateTime;
		this.scheduledTakeOffDateTime = scheduledTakeOffDateTime;
		this.estimatedTakeOffDateTime = estimatedTakeOffDateTime;
		this.actualTakeOffDateTime = actualTakeOffDateTime;
		this.scheduledFlyTime = scheduledFlyTime;
		this.estimatedFlyTime = estimatedFlyTime;
		this.actualDoorOpenDateTime = actualDoorOpenDateTime;
		this.actualDoorCloseDateTime = actualDoorCloseDateTime;
		this.actualOnBridgeDateTime = actualOnBridgeDateTime;
		this.actualOffBridgeDateTime = actualOffBridgeDateTime;
		this.bestKnownDateTime = bestKnownDateTime;
		this.flightStatus = flightStatus;
		this.operationStatus = operationStatus;
		this.delayReasonCode = delayReasonCode;
		this.delayReasonText = delayReasonText;
		this.publicTextComment = publicTextComment;
		this.createReason = createReason;
		this.diversionAirportIatacode = diversionAirportIatacode;
		this.diversionAirportIcaocode = diversionAirportIcaocode;
		this.changeLandingAirportIatacode = changeLandingAirportIatacode;
		this.changeLandingAirportIcaocode = changeLandingAirportIcaocode;
		this.displayCode = displayCode;
		this.isTransitFlight = isTransitFlight;
		this.isOverNightFlight = isOverNightFlight;
		this.isVipflight = isVipflight;
		this.vipcomment = vipcomment;
		this.stand = stand;
		this.groundMovement = groundMovement;
		this.gate = gate;
		this.gateStatus = gateStatus;
		this.scheduledGateStartDateTime = scheduledGateStartDateTime;
		this.scheduledGateEndDateTime = scheduledGateEndDateTime;
		this.actualGateStartDateTime = actualGateStartDateTime;
		this.actualGateEndDateTime = actualGateEndDateTime;
		this.baggageReclaim = baggageReclaim;
		this.baggageMakeup = baggageMakeup;
		this.checkInDesk = checkInDesk;
		this.checkInPassengerCount = checkInPassengerCount;
		this.securityCheckPassengerCount = securityCheckPassengerCount;
		this.onboardPassengerCount = onboardPassengerCount;
		this.createDateTime = createDateTime;
		this.updateDateTime = updateDateTime;
		this.fuid = fuid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getFlightScheduledDate() {
		return this.flightScheduledDate;
	}

	public void setFlightScheduledDate(Date flightScheduledDate) {
		this.flightScheduledDate = flightScheduledDate;
	}

	public String getFlightNumber() {
		return this.flightNumber;
	}

	public void setFlightNumber(String flightNumber) {
		this.flightNumber = flightNumber;
	}

	public String getFlightDirection() {
		return this.flightDirection;
	}

	public void setFlightDirection(String flightDirection) {
		this.flightDirection = flightDirection;
	}

	public String getAirlineIatacode() {
		return this.airlineIatacode;
	}

	public void setAirlineIatacode(String airlineIatacode) {
		this.airlineIatacode = airlineIatacode;
	}

	public String getAirlineIcaocode() {
		return this.airlineIcaocode;
	}

	public void setAirlineIcaocode(String airlineIcaocode) {
		this.airlineIcaocode = airlineIcaocode;
	}

	public String getAircraftIatacode() {
		return this.aircraftIatacode;
	}

	public void setAircraftIatacode(String aircraftIatacode) {
		this.aircraftIatacode = aircraftIatacode;
	}

	public String getAircraftIcaocode() {
		return this.aircraftIcaocode;
	}

	public void setAircraftIcaocode(String aircraftIcaocode) {
		this.aircraftIcaocode = aircraftIcaocode;
	}

	public String getFlightServiceType() {
		return this.flightServiceType;
	}

	public void setFlightServiceType(String flightServiceType) {
		this.flightServiceType = flightServiceType;
	}

	public String getFlightCountryType() {
		return this.flightCountryType;
	}

	public void setFlightCountryType(String flightCountryType) {
		this.flightCountryType = flightCountryType;
	}

	public Date getFlightScheduledDateTime() {
		return this.flightScheduledDateTime;
	}

	public void setFlightScheduledDateTime(Date flightScheduledDateTime) {
		this.flightScheduledDateTime = flightScheduledDateTime;
	}

	public String getRegistration() {
		return this.registration;
	}

	public void setRegistration(String registration) {
		this.registration = registration;
	}

	public String getCallSign() {
		return this.callSign;
	}

	public void setCallSign(String callSign) {
		this.callSign = callSign;
	}

	public String getCodeShareFlight() {
		return this.codeShareFlight;
	}

	public void setCodeShareFlight(String codeShareFlight) {
		this.codeShareFlight = codeShareFlight;
	}

	public String getIataoriginAirport() {
		return this.iataoriginAirport;
	}

	public void setIataoriginAirport(String iataoriginAirport) {
		this.iataoriginAirport = iataoriginAirport;
	}

	public String getIatapreviousAirport() {
		return this.iatapreviousAirport;
	}

	public void setIatapreviousAirport(String iatapreviousAirport) {
		this.iatapreviousAirport = iatapreviousAirport;
	}

	public String getIataviaAirport() {
		return this.iataviaAirport;
	}

	public void setIataviaAirport(String iataviaAirport) {
		this.iataviaAirport = iataviaAirport;
	}

	public String getIatanextAirport() {
		return this.iatanextAirport;
	}

	public void setIatanextAirport(String iatanextAirport) {
		this.iatanextAirport = iatanextAirport;
	}

	public String getIatadestinationAirport() {
		return this.iatadestinationAirport;
	}

	public void setIatadestinationAirport(String iatadestinationAirport) {
		this.iatadestinationAirport = iatadestinationAirport;
	}

	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	public Date getScheduledPreviousAirportDepartureDateTime() {
		return this.scheduledPreviousAirportDepartureDateTime;
	}

	public void setScheduledPreviousAirportDepartureDateTime(Date scheduledPreviousAirportDepartureDateTime) {
		this.scheduledPreviousAirportDepartureDateTime = scheduledPreviousAirportDepartureDateTime;
	}

	public Date getEstimatedPreviousAirportDepartureDateTime() {
		return this.estimatedPreviousAirportDepartureDateTime;
	}

	public void setEstimatedPreviousAirportDepartureDateTime(Date estimatedPreviousAirportDepartureDateTime) {
		this.estimatedPreviousAirportDepartureDateTime = estimatedPreviousAirportDepartureDateTime;
	}

	public Date getActualPreviousAirportDepartureDateTime() {
		return this.actualPreviousAirportDepartureDateTime;
	}

	public void setActualPreviousAirportDepartureDateTime(Date actualPreviousAirportDepartureDateTime) {
		this.actualPreviousAirportDepartureDateTime = actualPreviousAirportDepartureDateTime;
	}

	public Date getScheduledLandingDateTime() {
		return this.scheduledLandingDateTime;
	}

	public void setScheduledLandingDateTime(Date scheduledLandingDateTime) {
		this.scheduledLandingDateTime = scheduledLandingDateTime;
	}

	public Date getEstimatedLandingDateTime() {
		return this.estimatedLandingDateTime;
	}

	public void setEstimatedLandingDateTime(Date estimatedLandingDateTime) {
		this.estimatedLandingDateTime = estimatedLandingDateTime;
	}

	public Date getActualLandingDateTime() {
		return this.actualLandingDateTime;
	}

	public void setActualLandingDateTime(Date actualLandingDateTime) {
		this.actualLandingDateTime = actualLandingDateTime;
	}

	public Date getScheduledOnBlockDateTime() {
		return this.scheduledOnBlockDateTime;
	}

	public void setScheduledOnBlockDateTime(Date scheduledOnBlockDateTime) {
		this.scheduledOnBlockDateTime = scheduledOnBlockDateTime;
	}

	public Date getEstimatedOnBlockDateTime() {
		return this.estimatedOnBlockDateTime;
	}

	public void setEstimatedOnBlockDateTime(Date estimatedOnBlockDateTime) {
		this.estimatedOnBlockDateTime = estimatedOnBlockDateTime;
	}

	public Date getActualOnBlockDateTime() {
		return this.actualOnBlockDateTime;
	}

	public void setActualOnBlockDateTime(Date actualOnBlockDateTime) {
		this.actualOnBlockDateTime = actualOnBlockDateTime;
	}

	public Date getScheduledOffBlockDateTime() {
		return this.scheduledOffBlockDateTime;
	}

	public void setScheduledOffBlockDateTime(Date scheduledOffBlockDateTime) {
		this.scheduledOffBlockDateTime = scheduledOffBlockDateTime;
	}

	public Date getEstimatedOffBlockDateTime() {
		return this.estimatedOffBlockDateTime;
	}

	public void setEstimatedOffBlockDateTime(Date estimatedOffBlockDateTime) {
		this.estimatedOffBlockDateTime = estimatedOffBlockDateTime;
	}

	public Date getActualOffBlockDateTime() {
		return this.actualOffBlockDateTime;
	}

	public void setActualOffBlockDateTime(Date actualOffBlockDateTime) {
		this.actualOffBlockDateTime = actualOffBlockDateTime;
	}

	public Date getScheduledTakeOffDateTime() {
		return this.scheduledTakeOffDateTime;
	}

	public void setScheduledTakeOffDateTime(Date scheduledTakeOffDateTime) {
		this.scheduledTakeOffDateTime = scheduledTakeOffDateTime;
	}

	public Date getEstimatedTakeOffDateTime() {
		return this.estimatedTakeOffDateTime;
	}

	public void setEstimatedTakeOffDateTime(Date estimatedTakeOffDateTime) {
		this.estimatedTakeOffDateTime = estimatedTakeOffDateTime;
	}

	public Date getActualTakeOffDateTime() {
		return this.actualTakeOffDateTime;
	}

	public void setActualTakeOffDateTime(Date actualTakeOffDateTime) {
		this.actualTakeOffDateTime = actualTakeOffDateTime;
	}

	public Integer getScheduledFlyTime() {
		return this.scheduledFlyTime;
	}

	public void setScheduledFlyTime(Integer scheduledFlyTime) {
		this.scheduledFlyTime = scheduledFlyTime;
	}

	public Integer getEstimatedFlyTime() {
		return this.estimatedFlyTime;
	}

	public void setEstimatedFlyTime(Integer estimatedFlyTime) {
		this.estimatedFlyTime = estimatedFlyTime;
	}

	public Date getActualDoorOpenDateTime() {
		return this.actualDoorOpenDateTime;
	}

	public void setActualDoorOpenDateTime(Date actualDoorOpenDateTime) {
		this.actualDoorOpenDateTime = actualDoorOpenDateTime;
	}

	public Date getActualDoorCloseDateTime() {
		return this.actualDoorCloseDateTime;
	}

	public void setActualDoorCloseDateTime(Date actualDoorCloseDateTime) {
		this.actualDoorCloseDateTime = actualDoorCloseDateTime;
	}

	public Date getActualOnBridgeDateTime() {
		return this.actualOnBridgeDateTime;
	}

	public void setActualOnBridgeDateTime(Date actualOnBridgeDateTime) {
		this.actualOnBridgeDateTime = actualOnBridgeDateTime;
	}

	public Date getActualOffBridgeDateTime() {
		return this.actualOffBridgeDateTime;
	}

	public void setActualOffBridgeDateTime(Date actualOffBridgeDateTime) {
		this.actualOffBridgeDateTime = actualOffBridgeDateTime;
	}

	public Date getBestKnownDateTime() {
		return this.bestKnownDateTime;
	}

	public void setBestKnownDateTime(Date bestKnownDateTime) {
		this.bestKnownDateTime = bestKnownDateTime;
	}

	public String getFlightStatus() {
		return this.flightStatus;
	}

	public void setFlightStatus(String flightStatus) {
		this.flightStatus = flightStatus;
	}

	public String getOperationStatus() {
		return this.operationStatus;
	}

	public void setOperationStatus(String operationStatus) {
		this.operationStatus = operationStatus;
	}

	public String getDelayReasonCode() {
		return this.delayReasonCode;
	}

	public void setDelayReasonCode(String delayReasonCode) {
		this.delayReasonCode = delayReasonCode;
	}

	public String getDelayReasonText() {
		return this.delayReasonText;
	}

	public void setDelayReasonText(String delayReasonText) {
		this.delayReasonText = delayReasonText;
	}

	public String getPublicTextComment() {
		return this.publicTextComment;
	}

	public void setPublicTextComment(String publicTextComment) {
		this.publicTextComment = publicTextComment;
	}

	public String getCreateReason() {
		return this.createReason;
	}

	public void setCreateReason(String createReason) {
		this.createReason = createReason;
	}

	public String getDiversionAirportIatacode() {
		return this.diversionAirportIatacode;
	}

	public void setDiversionAirportIatacode(String diversionAirportIatacode) {
		this.diversionAirportIatacode = diversionAirportIatacode;
	}

	public String getDiversionAirportIcaocode() {
		return this.diversionAirportIcaocode;
	}

	public void setDiversionAirportIcaocode(String diversionAirportIcaocode) {
		this.diversionAirportIcaocode = diversionAirportIcaocode;
	}

	public String getChangeLandingAirportIatacode() {
		return this.changeLandingAirportIatacode;
	}

	public void setChangeLandingAirportIatacode(String changeLandingAirportIatacode) {
		this.changeLandingAirportIatacode = changeLandingAirportIatacode;
	}

	public String getChangeLandingAirportIcaocode() {
		return this.changeLandingAirportIcaocode;
	}

	public void setChangeLandingAirportIcaocode(String changeLandingAirportIcaocode) {
		this.changeLandingAirportIcaocode = changeLandingAirportIcaocode;
	}

	public String getDisplayCode() {
		return this.displayCode;
	}

	public void setDisplayCode(String displayCode) {
		this.displayCode = displayCode;
	}

	public String getIsTransitFlight() {
		return this.isTransitFlight;
	}

	public void setIsTransitFlight(String isTransitFlight) {
		this.isTransitFlight = isTransitFlight;
	}

	public String getIsOverNightFlight() {
		return this.isOverNightFlight;
	}

	public void setIsOverNightFlight(String isOverNightFlight) {
		this.isOverNightFlight = isOverNightFlight;
	}

	public String getIsVipflight() {
		return this.isVipflight;
	}

	public void setIsVipflight(String isVipflight) {
		this.isVipflight = isVipflight;
	}

	public String getVipcomment() {
		return this.vipcomment;
	}

	public void setVipcomment(String vipcomment) {
		this.vipcomment = vipcomment;
	}

	public String getStand() {
		return this.stand;
	}

	public void setStand(String stand) {
		this.stand = stand;
	}

	public String getGroundMovement() {
		return this.groundMovement;
	}

	public void setGroundMovement(String groundMovement) {
		this.groundMovement = groundMovement;
	}

	public String getGate() {
		return this.gate;
	}

	public void setGate(String gate) {
		this.gate = gate;
	}

	public String getGateStatus() {
		return this.gateStatus;
	}

	public void setGateStatus(String gateStatus) {
		this.gateStatus = gateStatus;
	}

	public Date getScheduledGateStartDateTime() {
		return this.scheduledGateStartDateTime;
	}

	public void setScheduledGateStartDateTime(Date scheduledGateStartDateTime) {
		this.scheduledGateStartDateTime = scheduledGateStartDateTime;
	}

	public Date getScheduledGateEndDateTime() {
		return this.scheduledGateEndDateTime;
	}

	public void setScheduledGateEndDateTime(Date scheduledGateEndDateTime) {
		this.scheduledGateEndDateTime = scheduledGateEndDateTime;
	}

	public Date getActualGateStartDateTime() {
		return this.actualGateStartDateTime;
	}

	public void setActualGateStartDateTime(Date actualGateStartDateTime) {
		this.actualGateStartDateTime = actualGateStartDateTime;
	}

	public Date getActualGateEndDateTime() {
		return this.actualGateEndDateTime;
	}

	public void setActualGateEndDateTime(Date actualGateEndDateTime) {
		this.actualGateEndDateTime = actualGateEndDateTime;
	}

	public String getBaggageReclaim() {
		return this.baggageReclaim;
	}

	public void setBaggageReclaim(String baggageReclaim) {
		this.baggageReclaim = baggageReclaim;
	}

	public String getBaggageMakeup() {
		return this.baggageMakeup;
	}

	public void setBaggageMakeup(String baggageMakeup) {
		this.baggageMakeup = baggageMakeup;
	}

	public String getCheckInDesk() {
		return this.checkInDesk;
	}

	public void setCheckInDesk(String checkInDesk) {
		this.checkInDesk = checkInDesk;
	}

	public Integer getCheckInPassengerCount() {
		return this.checkInPassengerCount;
	}

	public void setCheckInPassengerCount(Integer checkInPassengerCount) {
		this.checkInPassengerCount = checkInPassengerCount;
	}

	public Integer getSecurityCheckPassengerCount() {
		return this.securityCheckPassengerCount;
	}

	public void setSecurityCheckPassengerCount(Integer securityCheckPassengerCount) {
		this.securityCheckPassengerCount = securityCheckPassengerCount;
	}

	public Integer getOnboardPassengerCount() {
		return this.onboardPassengerCount;
	}

	public void setOnboardPassengerCount(Integer onboardPassengerCount) {
		this.onboardPassengerCount = onboardPassengerCount;
	}

	public Date getCreateDateTime() {
		return this.createDateTime;
	}

	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}

	public Date getUpdateDateTime() {
		return this.updateDateTime;
	}

	public void setUpdateDateTime(Date updateDateTime) {
		this.updateDateTime = updateDateTime;
	}

	public String getFuid() {
		return this.fuid;
	}

	public void setFuid(String fuid) {
		this.fuid = fuid;
	}

}
