package com.tsystems.si.aviation.imf.vzHandle.db.bean;
// Generated Jun 23, 2016 4:34:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ImfMessage generated by hbm2java
 */
public class ImfMessage implements java.io.Serializable {

	private Integer id;
	private OrgMessage orgMessage;
	private String fileName;
	private String xmlMessage;
	private String status;
	private String operationStatus;
	private String reason;
	private String flightNumber;
	private String flightDirection;
	private Date flightScheduledDate;
	private Date flightScheduledDateTime;
	private String registration;
	private Date scheduledPreviousAirportDepartureDateTime;
	private Date estimatedPreviousAirportDepartureDateTime;
	private Date actualPreviousAirportDepartureDateTime;
	private Date scheduledLandingDateTime;
	private Date estimatedLandingDateTime;
	private Date actualLandingDateTime;
	private Date scheduledOnBlockDateTime;
	private Date estimatedOnBlockDateTime;
	private Date actualOnBlockDateTime;
	private Date scheduledOffBlockDateTime;
	private Date estimatedOffBlockDateTime;
	private Date actualOffBlockDateTime;
	private Date scheduledTakeOffDateTime;
	private Date estimatedTakeOffDateTime;
	private Date actualTakeOffDateTime;
	private Date scheduledNextAirportArrivalDateTime;
	private Date estimatedNextAirportDepartureDateTime;
	private Date actualNextAirportDepartureDateTime;
	private Date createDateTime;
	private Date updateDateTime;
	private Date sendDateTime;
	private String owner;
	private String sender;

	public ImfMessage() {
	}

	public ImfMessage(OrgMessage orgMessage, String fileName, String xmlMessage, String status, String operationStatus,
			String reason, String flightNumber, String flightDirection, Date flightScheduledDate,
			Date flightScheduledDateTime, String registration, Date scheduledPreviousAirportDepartureDateTime,
			Date estimatedPreviousAirportDepartureDateTime, Date actualPreviousAirportDepartureDateTime,
			Date scheduledLandingDateTime, Date estimatedLandingDateTime, Date actualLandingDateTime,
			Date scheduledOnBlockDateTime, Date estimatedOnBlockDateTime, Date actualOnBlockDateTime,
			Date scheduledOffBlockDateTime, Date estimatedOffBlockDateTime, Date actualOffBlockDateTime,
			Date scheduledTakeOffDateTime, Date estimatedTakeOffDateTime, Date actualTakeOffDateTime,
			Date scheduledNextAirportArrivalDateTime, Date estimatedNextAirportDepartureDateTime,
			Date actualNextAirportDepartureDateTime, Date createDateTime, Date updateDateTime, Date sendDateTime,
			String owner, String sender) {
		this.orgMessage = orgMessage;
		this.fileName = fileName;
		this.xmlMessage = xmlMessage;
		this.status = status;
		this.operationStatus = operationStatus;
		this.reason = reason;
		this.flightNumber = flightNumber;
		this.flightDirection = flightDirection;
		this.flightScheduledDate = flightScheduledDate;
		this.flightScheduledDateTime = flightScheduledDateTime;
		this.registration = registration;
		this.scheduledPreviousAirportDepartureDateTime = scheduledPreviousAirportDepartureDateTime;
		this.estimatedPreviousAirportDepartureDateTime = estimatedPreviousAirportDepartureDateTime;
		this.actualPreviousAirportDepartureDateTime = actualPreviousAirportDepartureDateTime;
		this.scheduledLandingDateTime = scheduledLandingDateTime;
		this.estimatedLandingDateTime = estimatedLandingDateTime;
		this.actualLandingDateTime = actualLandingDateTime;
		this.scheduledOnBlockDateTime = scheduledOnBlockDateTime;
		this.estimatedOnBlockDateTime = estimatedOnBlockDateTime;
		this.actualOnBlockDateTime = actualOnBlockDateTime;
		this.scheduledOffBlockDateTime = scheduledOffBlockDateTime;
		this.estimatedOffBlockDateTime = estimatedOffBlockDateTime;
		this.actualOffBlockDateTime = actualOffBlockDateTime;
		this.scheduledTakeOffDateTime = scheduledTakeOffDateTime;
		this.estimatedTakeOffDateTime = estimatedTakeOffDateTime;
		this.actualTakeOffDateTime = actualTakeOffDateTime;
		this.scheduledNextAirportArrivalDateTime = scheduledNextAirportArrivalDateTime;
		this.estimatedNextAirportDepartureDateTime = estimatedNextAirportDepartureDateTime;
		this.actualNextAirportDepartureDateTime = actualNextAirportDepartureDateTime;
		this.createDateTime = createDateTime;
		this.updateDateTime = updateDateTime;
		this.sendDateTime = sendDateTime;
		this.owner = owner;
		this.sender = sender;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public OrgMessage getOrgMessage() {
		return this.orgMessage;
	}

	public void setOrgMessage(OrgMessage orgMessage) {
		this.orgMessage = orgMessage;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getXmlMessage() {
		return this.xmlMessage;
	}

	public void setXmlMessage(String xmlMessage) {
		this.xmlMessage = xmlMessage;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getOperationStatus() {
		return this.operationStatus;
	}

	public void setOperationStatus(String operationStatus) {
		this.operationStatus = operationStatus;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getFlightNumber() {
		return this.flightNumber;
	}

	public void setFlightNumber(String flightNumber) {
		this.flightNumber = flightNumber;
	}

	public String getFlightDirection() {
		return this.flightDirection;
	}

	public void setFlightDirection(String flightDirection) {
		this.flightDirection = flightDirection;
	}

	public Date getFlightScheduledDate() {
		return this.flightScheduledDate;
	}

	public void setFlightScheduledDate(Date flightScheduledDate) {
		this.flightScheduledDate = flightScheduledDate;
	}

	public Date getFlightScheduledDateTime() {
		return this.flightScheduledDateTime;
	}

	public void setFlightScheduledDateTime(Date flightScheduledDateTime) {
		this.flightScheduledDateTime = flightScheduledDateTime;
	}

	public String getRegistration() {
		return this.registration;
	}

	public void setRegistration(String registration) {
		this.registration = registration;
	}

	public Date getScheduledPreviousAirportDepartureDateTime() {
		return this.scheduledPreviousAirportDepartureDateTime;
	}

	public void setScheduledPreviousAirportDepartureDateTime(Date scheduledPreviousAirportDepartureDateTime) {
		this.scheduledPreviousAirportDepartureDateTime = scheduledPreviousAirportDepartureDateTime;
	}

	public Date getEstimatedPreviousAirportDepartureDateTime() {
		return this.estimatedPreviousAirportDepartureDateTime;
	}

	public void setEstimatedPreviousAirportDepartureDateTime(Date estimatedPreviousAirportDepartureDateTime) {
		this.estimatedPreviousAirportDepartureDateTime = estimatedPreviousAirportDepartureDateTime;
	}

	public Date getActualPreviousAirportDepartureDateTime() {
		return this.actualPreviousAirportDepartureDateTime;
	}

	public void setActualPreviousAirportDepartureDateTime(Date actualPreviousAirportDepartureDateTime) {
		this.actualPreviousAirportDepartureDateTime = actualPreviousAirportDepartureDateTime;
	}

	public Date getScheduledLandingDateTime() {
		return this.scheduledLandingDateTime;
	}

	public void setScheduledLandingDateTime(Date scheduledLandingDateTime) {
		this.scheduledLandingDateTime = scheduledLandingDateTime;
	}

	public Date getEstimatedLandingDateTime() {
		return this.estimatedLandingDateTime;
	}

	public void setEstimatedLandingDateTime(Date estimatedLandingDateTime) {
		this.estimatedLandingDateTime = estimatedLandingDateTime;
	}

	public Date getActualLandingDateTime() {
		return this.actualLandingDateTime;
	}

	public void setActualLandingDateTime(Date actualLandingDateTime) {
		this.actualLandingDateTime = actualLandingDateTime;
	}

	public Date getScheduledOnBlockDateTime() {
		return this.scheduledOnBlockDateTime;
	}

	public void setScheduledOnBlockDateTime(Date scheduledOnBlockDateTime) {
		this.scheduledOnBlockDateTime = scheduledOnBlockDateTime;
	}

	public Date getEstimatedOnBlockDateTime() {
		return this.estimatedOnBlockDateTime;
	}

	public void setEstimatedOnBlockDateTime(Date estimatedOnBlockDateTime) {
		this.estimatedOnBlockDateTime = estimatedOnBlockDateTime;
	}

	public Date getActualOnBlockDateTime() {
		return this.actualOnBlockDateTime;
	}

	public void setActualOnBlockDateTime(Date actualOnBlockDateTime) {
		this.actualOnBlockDateTime = actualOnBlockDateTime;
	}

	public Date getScheduledOffBlockDateTime() {
		return this.scheduledOffBlockDateTime;
	}

	public void setScheduledOffBlockDateTime(Date scheduledOffBlockDateTime) {
		this.scheduledOffBlockDateTime = scheduledOffBlockDateTime;
	}

	public Date getEstimatedOffBlockDateTime() {
		return this.estimatedOffBlockDateTime;
	}

	public void setEstimatedOffBlockDateTime(Date estimatedOffBlockDateTime) {
		this.estimatedOffBlockDateTime = estimatedOffBlockDateTime;
	}

	public Date getActualOffBlockDateTime() {
		return this.actualOffBlockDateTime;
	}

	public void setActualOffBlockDateTime(Date actualOffBlockDateTime) {
		this.actualOffBlockDateTime = actualOffBlockDateTime;
	}

	public Date getScheduledTakeOffDateTime() {
		return this.scheduledTakeOffDateTime;
	}

	public void setScheduledTakeOffDateTime(Date scheduledTakeOffDateTime) {
		this.scheduledTakeOffDateTime = scheduledTakeOffDateTime;
	}

	public Date getEstimatedTakeOffDateTime() {
		return this.estimatedTakeOffDateTime;
	}

	public void setEstimatedTakeOffDateTime(Date estimatedTakeOffDateTime) {
		this.estimatedTakeOffDateTime = estimatedTakeOffDateTime;
	}

	public Date getActualTakeOffDateTime() {
		return this.actualTakeOffDateTime;
	}

	public void setActualTakeOffDateTime(Date actualTakeOffDateTime) {
		this.actualTakeOffDateTime = actualTakeOffDateTime;
	}

	public Date getScheduledNextAirportArrivalDateTime() {
		return this.scheduledNextAirportArrivalDateTime;
	}

	public void setScheduledNextAirportArrivalDateTime(Date scheduledNextAirportArrivalDateTime) {
		this.scheduledNextAirportArrivalDateTime = scheduledNextAirportArrivalDateTime;
	}

	public Date getEstimatedNextAirportDepartureDateTime() {
		return this.estimatedNextAirportDepartureDateTime;
	}

	public void setEstimatedNextAirportDepartureDateTime(Date estimatedNextAirportDepartureDateTime) {
		this.estimatedNextAirportDepartureDateTime = estimatedNextAirportDepartureDateTime;
	}

	public Date getActualNextAirportDepartureDateTime() {
		return this.actualNextAirportDepartureDateTime;
	}

	public void setActualNextAirportDepartureDateTime(Date actualNextAirportDepartureDateTime) {
		this.actualNextAirportDepartureDateTime = actualNextAirportDepartureDateTime;
	}

	public Date getCreateDateTime() {
		return this.createDateTime;
	}

	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}

	public Date getUpdateDateTime() {
		return this.updateDateTime;
	}

	public void setUpdateDateTime(Date updateDateTime) {
		this.updateDateTime = updateDateTime;
	}

	public Date getSendDateTime() {
		return this.sendDateTime;
	}

	public void setSendDateTime(Date sendDateTime) {
		this.sendDateTime = sendDateTime;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

}
