package com.tsystems.si.aviation.imf.vzHandle.db.bean;
// Generated Jun 23, 2016 4:34:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrgMessage generated by hbm2java
 */
public class OrgMessage implements java.io.Serializable {

	private Integer id;
	private String owner;
	private String type;
	private String subtype;
	private String fullPath;
	private String fileName;
	private String mvn;
	private String status;
	private String comments;
	private String content;
	private Date generateDateTime;
	private Date createDateTime;
	private Date updateDateTime;
	private Set imfMessages = new HashSet(0);

	public OrgMessage() {
	}

	public OrgMessage(String owner, String type, String subtype, String fullPath, String fileName, String mvn,
			String status, String comments, String content, Date generateDateTime, Date createDateTime,
			Date updateDateTime, Set imfMessages) {
		this.owner = owner;
		this.type = type;
		this.subtype = subtype;
		this.fullPath = fullPath;
		this.fileName = fileName;
		this.mvn = mvn;
		this.status = status;
		this.comments = comments;
		this.content = content;
		this.generateDateTime = generateDateTime;
		this.createDateTime = createDateTime;
		this.updateDateTime = updateDateTime;
		this.imfMessages = imfMessages;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSubtype() {
		return this.subtype;
	}

	public void setSubtype(String subtype) {
		this.subtype = subtype;
	}

	public String getFullPath() {
		return this.fullPath;
	}

	public void setFullPath(String fullPath) {
		this.fullPath = fullPath;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getMvn() {
		return this.mvn;
	}

	public void setMvn(String mvn) {
		this.mvn = mvn;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getGenerateDateTime() {
		return this.generateDateTime;
	}

	public void setGenerateDateTime(Date generateDateTime) {
		this.generateDateTime = generateDateTime;
	}

	public Date getCreateDateTime() {
		return this.createDateTime;
	}

	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}

	public Date getUpdateDateTime() {
		return this.updateDateTime;
	}

	public void setUpdateDateTime(Date updateDateTime) {
		this.updateDateTime = updateDateTime;
	}

	public Set getImfMessages() {
		return this.imfMessages;
	}

	public void setImfMessages(Set imfMessages) {
		this.imfMessages = imfMessages;
	}

}
