package com.tsystems.si.aviation.imf.vzHandle.db.bean;
// Generated Jun 23, 2016 4:34:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * RefAirline generated by hbm2java
 */
public class RefAirline implements java.io.Serializable {

	private Integer id;
	private String airlineIatacode;
	private String airlineIcaocode;
	private String airlineName;
	private String airlineHomeCountry;
	private String airlineAllianceGroup;
	private String airlineDescription;
	private String airlineHandler;
	private Date createDateTime;
	private Date updateDateTime;

	public RefAirline() {
	}

	public RefAirline(String airlineIatacode, String airlineIcaocode, String airlineName, String airlineHomeCountry,
			String airlineAllianceGroup, String airlineDescription, String airlineHandler, Date createDateTime,
			Date updateDateTime) {
		this.airlineIatacode = airlineIatacode;
		this.airlineIcaocode = airlineIcaocode;
		this.airlineName = airlineName;
		this.airlineHomeCountry = airlineHomeCountry;
		this.airlineAllianceGroup = airlineAllianceGroup;
		this.airlineDescription = airlineDescription;
		this.airlineHandler = airlineHandler;
		this.createDateTime = createDateTime;
		this.updateDateTime = updateDateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAirlineIatacode() {
		return this.airlineIatacode;
	}

	public void setAirlineIatacode(String airlineIatacode) {
		this.airlineIatacode = airlineIatacode;
	}

	public String getAirlineIcaocode() {
		return this.airlineIcaocode;
	}

	public void setAirlineIcaocode(String airlineIcaocode) {
		this.airlineIcaocode = airlineIcaocode;
	}

	public String getAirlineName() {
		return this.airlineName;
	}

	public void setAirlineName(String airlineName) {
		this.airlineName = airlineName;
	}

	public String getAirlineHomeCountry() {
		return this.airlineHomeCountry;
	}

	public void setAirlineHomeCountry(String airlineHomeCountry) {
		this.airlineHomeCountry = airlineHomeCountry;
	}

	public String getAirlineAllianceGroup() {
		return this.airlineAllianceGroup;
	}

	public void setAirlineAllianceGroup(String airlineAllianceGroup) {
		this.airlineAllianceGroup = airlineAllianceGroup;
	}

	public String getAirlineDescription() {
		return this.airlineDescription;
	}

	public void setAirlineDescription(String airlineDescription) {
		this.airlineDescription = airlineDescription;
	}

	public String getAirlineHandler() {
		return this.airlineHandler;
	}

	public void setAirlineHandler(String airlineHandler) {
		this.airlineHandler = airlineHandler;
	}

	public Date getCreateDateTime() {
		return this.createDateTime;
	}

	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}

	public Date getUpdateDateTime() {
		return this.updateDateTime;
	}

	public void setUpdateDateTime(Date updateDateTime) {
		this.updateDateTime = updateDateTime;
	}

}
