package com.tsystems.si.aviation.imf.vzHandle.db.bean;
// Generated Jun 23, 2016 4:34:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * RefAirport generated by hbm2java
 */
public class RefAirport implements java.io.Serializable {

	private Integer id;
	private String airportIatacode;
	private String airportIcaocode;
	private String airportChineseShortName;
	private String airportChineseFullName;
	private String airportEnglishShortName;
	private String airportEnglishFullName;
	private String airportRoutingName;
	private String airportCountry;
	private String airportCountryType;
	private String airportCity;
	private String airportRegion;
	private String airportTimezone;
	private Integer airportDistance;
	private String airportdescription;
	private Date createDateTime;
	private Date updateDateTime;

	public RefAirport() {
	}

	public RefAirport(String airportIatacode, String airportIcaocode, String airportChineseShortName,
			String airportChineseFullName, String airportEnglishShortName, String airportEnglishFullName,
			String airportRoutingName, String airportCountry, String airportCountryType, String airportCity,
			String airportRegion, String airportTimezone, Integer airportDistance, String airportdescription,
			Date createDateTime, Date updateDateTime) {
		this.airportIatacode = airportIatacode;
		this.airportIcaocode = airportIcaocode;
		this.airportChineseShortName = airportChineseShortName;
		this.airportChineseFullName = airportChineseFullName;
		this.airportEnglishShortName = airportEnglishShortName;
		this.airportEnglishFullName = airportEnglishFullName;
		this.airportRoutingName = airportRoutingName;
		this.airportCountry = airportCountry;
		this.airportCountryType = airportCountryType;
		this.airportCity = airportCity;
		this.airportRegion = airportRegion;
		this.airportTimezone = airportTimezone;
		this.airportDistance = airportDistance;
		this.airportdescription = airportdescription;
		this.createDateTime = createDateTime;
		this.updateDateTime = updateDateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAirportIatacode() {
		return this.airportIatacode;
	}

	public void setAirportIatacode(String airportIatacode) {
		this.airportIatacode = airportIatacode;
	}

	public String getAirportIcaocode() {
		return this.airportIcaocode;
	}

	public void setAirportIcaocode(String airportIcaocode) {
		this.airportIcaocode = airportIcaocode;
	}

	public String getAirportChineseShortName() {
		return this.airportChineseShortName;
	}

	public void setAirportChineseShortName(String airportChineseShortName) {
		this.airportChineseShortName = airportChineseShortName;
	}

	public String getAirportChineseFullName() {
		return this.airportChineseFullName;
	}

	public void setAirportChineseFullName(String airportChineseFullName) {
		this.airportChineseFullName = airportChineseFullName;
	}

	public String getAirportEnglishShortName() {
		return this.airportEnglishShortName;
	}

	public void setAirportEnglishShortName(String airportEnglishShortName) {
		this.airportEnglishShortName = airportEnglishShortName;
	}

	public String getAirportEnglishFullName() {
		return this.airportEnglishFullName;
	}

	public void setAirportEnglishFullName(String airportEnglishFullName) {
		this.airportEnglishFullName = airportEnglishFullName;
	}

	public String getAirportRoutingName() {
		return this.airportRoutingName;
	}

	public void setAirportRoutingName(String airportRoutingName) {
		this.airportRoutingName = airportRoutingName;
	}

	public String getAirportCountry() {
		return this.airportCountry;
	}

	public void setAirportCountry(String airportCountry) {
		this.airportCountry = airportCountry;
	}

	public String getAirportCountryType() {
		return this.airportCountryType;
	}

	public void setAirportCountryType(String airportCountryType) {
		this.airportCountryType = airportCountryType;
	}

	public String getAirportCity() {
		return this.airportCity;
	}

	public void setAirportCity(String airportCity) {
		this.airportCity = airportCity;
	}

	public String getAirportRegion() {
		return this.airportRegion;
	}

	public void setAirportRegion(String airportRegion) {
		this.airportRegion = airportRegion;
	}

	public String getAirportTimezone() {
		return this.airportTimezone;
	}

	public void setAirportTimezone(String airportTimezone) {
		this.airportTimezone = airportTimezone;
	}

	public Integer getAirportDistance() {
		return this.airportDistance;
	}

	public void setAirportDistance(Integer airportDistance) {
		this.airportDistance = airportDistance;
	}

	public String getAirportdescription() {
		return this.airportdescription;
	}

	public void setAirportdescription(String airportdescription) {
		this.airportdescription = airportdescription;
	}

	public Date getCreateDateTime() {
		return this.createDateTime;
	}

	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}

	public Date getUpdateDateTime() {
		return this.updateDateTime;
	}

	public void setUpdateDateTime(Date updateDateTime) {
		this.updateDateTime = updateDateTime;
	}

}
