package com.tsystems.si.aviation.imf.vzHandle.db.bean;
// Generated Jun 23, 2016 4:34:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * SysParameter generated by hbm2java
 */
public class SysParameter implements java.io.Serializable {

	private String spName;
	private String spDescription;
	private String spValue1;
	private String spValue2;
	private String spValue3;
	private String spValue4;
	private String createUser;
	private String updateUser;
	private Date createDateTime;
	private Date updateDateTime;

	public SysParameter() {
	}

	public SysParameter(String spName) {
		this.spName = spName;
	}

	public SysParameter(String spName, String spDescription, String spValue1, String spValue2, String spValue3,
			String spValue4, String createUser, String updateUser, Date createDateTime, Date updateDateTime) {
		this.spName = spName;
		this.spDescription = spDescription;
		this.spValue1 = spValue1;
		this.spValue2 = spValue2;
		this.spValue3 = spValue3;
		this.spValue4 = spValue4;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.createDateTime = createDateTime;
		this.updateDateTime = updateDateTime;
	}

	public String getSpName() {
		return this.spName;
	}

	public void setSpName(String spName) {
		this.spName = spName;
	}

	public String getSpDescription() {
		return this.spDescription;
	}

	public void setSpDescription(String spDescription) {
		this.spDescription = spDescription;
	}

	public String getSpValue1() {
		return this.spValue1;
	}

	public void setSpValue1(String spValue1) {
		this.spValue1 = spValue1;
	}

	public String getSpValue2() {
		return this.spValue2;
	}

	public void setSpValue2(String spValue2) {
		this.spValue2 = spValue2;
	}

	public String getSpValue3() {
		return this.spValue3;
	}

	public void setSpValue3(String spValue3) {
		this.spValue3 = spValue3;
	}

	public String getSpValue4() {
		return this.spValue4;
	}

	public void setSpValue4(String spValue4) {
		this.spValue4 = spValue4;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getCreateDateTime() {
		return this.createDateTime;
	}

	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}

	public Date getUpdateDateTime() {
		return this.updateDateTime;
	}

	public void setUpdateDateTime(Date updateDateTime) {
		this.updateDateTime = updateDateTime;
	}

}
